---
title: "Introduction"
toc: false
---

Welcome to **Data Dispatches**, the online portal for [JHU Data Services](https://dataservices.library.jhu.edu/) data tutorials. Here you will find short tutorials, primarily in R and Python, on a number of data related topics including access, cleaning, analysis, and visualization.

Topics are organized into themes, with individual topics called **dispatches**.

### What's a Dispatch?

Dispatches are short tutorials on a number of data subjects. Use the navigation on the left to find tutorials of interest, or use the search function in the top of the sidebar.

| Topic                                                    | Description                                                        |
|--------------------|----------------------------------------------------|
| 📊 Data Visualization                                    | Topics in Data Visualization, primarily in the R library `ggplot2` |
| 👩🏻‍💻 [API Guides](./dispatches/data-access/api-guides.qmd) | API examples for common open data sources and JHU databases        |
|                                                          |                                                                    |

::: callout-note
# New dispatches are added frequently, so check back regularly for new tutorials!
:::

### About Data Services

<iframe width="560" height="315" src="https://www.youtube.com/embed/r4VqNMw6Q8s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>
